#' Generate an overview of all project milestones
#'
#' If you used `projectlog::log_milestones` throughout our project, this
#' function can be used to summarise them in a bulleted list. By default,
#' this function is included in the top-level README file as generated by
#' `projectlog`. If you did not use `projectlog` to generate your project,
#' you can run this function to generate the milestone overview and paste it
#' in a location of your choice.
#' @param copy Boolean. If TRUE, the bulleted overview of milestones is
#' copied to the clipboard.
#' @return A bulleted overview of the project milestones, including the type of
#' milestone (e.g., first-time data access, timestamped preregistration), a link
#' to the GitHub commit, and (in the case of first-time data access) the unique
#' MD5 hash of the data read into the R environment, as well as a link to the
#' code that was used to read the data.
#' @importFrom rlang .data
#' @export
generate_milestone_overview <- function(copy = FALSE) {

  milestones <- gert::git_tag_list() |>
    dplyr::mutate(
      tags = purrr::pmap(list(name = .data$name, ref = .data$ref, commit = .data$commit), function(name, ref, commit) {
        gert::git_commit_info(.data$commit) |>
          tidyr::as_tibble() |>
          dplyr::select(commit = .data$id, .data$author, .data$time, .data$message)
      })
    ) |>
    dplyr::select(-.data$commit, -.data$ref) |>
    tidyr::unnest(.data$tags) |>
    tidyr::separate(.data$message, into = c("description", "hash", "code"), sep = "\\n") |>
    dplyr::mutate(
      branch = gert::git_branch_list() |> dplyr::filter(local == TRUE) |> dplyr::pull(.data$name),
      name = purrr::map_chr(.data$name, function(name) {
        name |>
          stringr::str_remove("\\d*$") |>
          stringr::str_replace("_", " ") |>
          stringr::str_to_title()
      }),
      code = ifelse(.data$name == "Data Access", stringr::str_remove_all(.data$code, "^code\\s") |> stringr::str_replace_all(string = _, "\\|\\>", "\\|\\>\\\n"), "Not applicable"),
      link_to_git = ifelse(.data$name == 'Data Access',
                           paste0(get_git_url(), "/blob/", .data$branch, "/", .data$commit, ".R"),
                           paste0(get_git_url(), "/tree/", .data$commit)
      ),
      hash = ifelse(.data$name != "Data Access", "Not applicable", .data$hash),

    ) |>
    dplyr::arrange(dplyr::desc(.data$time))

  # Write scripts including code to .projectlog folder
  milestones |>
    purrr::pwalk(function(name,commit,author,time,description,hash,code,branch,link_to_git){

      if(name == "Data Access"){
        code <- code |>
          stringr::str_replace_all(string = _, "\\|> ", "\\|>\n") |>
          stringr::str_remove(string = _, "^code ")

        url <- get_git_url() |>
          paste0("/commit/", .data$commit)

        script <-
          glue::glue(
            "
          ### Date: {time}\n
          ### Description: {description}\n\n
          ### For more information on this commit, see the README file, or go to {url}\n
          ### Below is the full code that was used to access the data:\n\n
          {code}"
          )

        writeLines(script, con = paste0(".projectlog/", .data$commit, ".R"))
      }
    })

  # Print milestones
  glue::glue_data(milestones, "  - **[{time}]({link_to_git}): {description}**
        - **Milestone:** {name}
        - **Data MD5 hash**: {hash}
        - [Link to code snippet]({link_to_git})
        \n
    ")


}

